### PR TITLE
(RE-5642) Adding pxpagent - first pass

### PR DESCRIPTION
**Pull request by jcoconnor**
(RE-5642) First pass at adding pxpagent to the build.

### CODE REVIEW

**Comment by ferventcoder** [comment]
This probably also needs the updates to a sample yaml file to see how this is intended to be added.

**Comment by ferventcoder** [comment]
I'm guessing it is just a zip file for the most part that would be added that would download the agent and grab the files it uses to produce the wxs file (heat).

**Comment by jcoconnor** [comment]
Amended comment in commit to add ticket number.

@ferventcoder Can you elaborate on what you are looking for with a sample yaml file ?

This change is associated with PR https://github.com/puppetlabs/puppet-agent/pull/311 which generates a pxp-agent.zip containing the pxp-agent assets for staging.

**Comment by ferventcoder** [comment]
@jcoconnor sure thing - take a look at all of the yaml files in the top level directory of this repo (https://github.com/puppetlabs/puppet_for_the_win). Edit one of them to add the zip archive details

**Pull request merged**
