### PR TITLE
Revert "(maint) Ensure there are no spaces in the msi name"

### PR DESCRIPTION
**Pull request by melissa**
This reverts commit f6584df2d8f1a9318ae4a8448d9d2a64237743cb.

### CODE REVIEW

**Comment by ferventcoder** [comment]
:-1: Don't see what this hurts.

**Comment by ferventcoder** [comment]
I don't have a problem guarding against user input.

**Comment by haus** [comment]
@melissa it's unclear from the commit message why this should be reverted

**Comment by Iristyle** [comment]
I think the problem was that it covered problems in how build parameters were passed through the pipeline, so I'm :+1: to merging this.

**Comment by melissa** [comment]
@Iristyle @ferventcoder commit message updated. I'm fine with either leaving this in, or pulling it out. Whatever seems to make more sense.

**Comment by melissa** [comment]
@ferventcoder @Iristyle any advice on how to move forward with this? I'd like to resolve the ticket.

**Comment by ferventcoder** [comment]
LGTM. I'm +1 to merging

**Pull request merged**
